//! `McpHandler` — the `rmcp` `ServerHandler` implementation for localdb.
//!
//! Tool routing (`tools/list`, `tools/call`) is entirely macro-generated by
//! `#[tool_router]`/`#[tool_handler]`; there is no hand-written dispatch
//! table. Each `#[tool]` method here is a thin `Parameters<T>` → `tools::*`
//! forwarder — all validation and business logic lives in `tools.rs`,
//! unchanged from the pre-rmcp implementation.

use std::sync::Arc;

use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{CallToolResult, Implementation, ServerCapabilities, ServerInfo},
    tool, tool_handler, tool_router, ServerHandler,
};

use localdb_core::{Embedder, StoreBackend};

use crate::args::{GetChunksArgs, GetDocumentArgs, ListDocumentsArgs, SearchArgs};
use crate::tools::{self, AvailableStore};

/// Embedded-stdio MCP server handler: holds the resolved stores, the
/// backend `get_document`/`list_documents` resolve document registry rows
/// through, the embedder used for `search`, and whether `--allow-write` was
/// passed (parsed but always rejected in v1 — no mutating tool is
/// registered).
///
/// `backend` and `stores` are threaded separately rather than one replacing
/// the other: `stores` (each an `AvailableStore` — a session-scoped
/// `RetrievalStore` handle) is what `search`/`get_chunks`/`list_stores`
/// query directly, while `backend` is the shared `StoreBackend` those
/// `AvailableStore` handles were themselves resolved from — `get_document`/
/// `list_documents` need it for the document-registry lookups
/// (`StoreBackend::find_document`/`list_documents`) `RetrievalStore` doesn't
/// expose. Every tool still resolves a caller-supplied store name through
/// `stores` (via `tools::select_mcp_stores`) before it ever reaches
/// `backend`, so `--store` session scoping is unaffected by this field's
/// presence — see `tools::get_document_from_store`/`tool_list_documents`.
#[derive(Clone)]
pub struct McpHandler {
    pub stores: Vec<AvailableStore>,
    pub backend: Arc<dyn StoreBackend>,
    pub embedder: Arc<dyn Embedder>,
    pub allow_write: bool,
    tool_router: ToolRouter<Self>,
}

impl McpHandler {
    /// Create a new handler over the given stores, backend, and embedder.
    pub fn new(
        stores: Vec<AvailableStore>,
        backend: Arc<dyn StoreBackend>,
        embedder: Arc<dyn Embedder>,
        allow_write: bool,
    ) -> Self {
        Self {
            stores,
            backend,
            embedder,
            allow_write,
            tool_router: Self::tool_router(),
        }
    }
}

#[tool_router]
impl McpHandler {
    /// Hybrid search (BM25 + dense vector) across indexed stores. Returns a
    /// ranked list of citations in the canonical localdb Citation JSON shape.
    #[tool(
        description = "Hybrid search (BM25 + dense vector) across indexed stores. Returns a ranked list of citations in the canonical localdb Citation JSON shape."
    )]
    async fn search(&self, Parameters(args): Parameters<SearchArgs>) -> CallToolResult {
        tools::tool_search(&self.stores, self.embedder.as_ref(), args).await
    }

    /// Fetch the normalized text and metadata for a document by its ID.
    #[tool(
        description = "Fetch the normalized text and metadata for a document by its ID or URI. Pass 'store' (id or name, e.g. from a search citation) to disambiguate when the same document id exists in multiple stores."
    )]
    async fn get_document(&self, Parameters(args): Parameters<GetDocumentArgs>) -> CallToolResult {
        tools::tool_get_document(&self.stores, self.backend.as_ref(), args).await
    }

    /// Fetch a document's chunks in order, paginated by offset/limit or by
    /// an anchor (anchor_chunk_id / anchor_block_seq) centered window.
    #[tool(
        description = "Fetch a document's chunks in order (block_seq, seq_in_block), paginated by offset/limit, or by an anchor_chunk_id/anchor_block_seq centered window (mutually exclusive with offset and with each other). Pass 'store' (id or name, e.g. from a search citation) to disambiguate when the same document id exists in multiple stores."
    )]
    async fn get_chunks(&self, Parameters(args): Parameters<GetChunksArgs>) -> CallToolResult {
        tools::tool_get_chunks(&self.stores, args).await
    }

    /// List all available stores with their names, visibility, and
    /// document/chunk counts.
    #[tool(
        description = "List all available stores with their names, visibility, and document/chunk counts."
    )]
    async fn list_stores(&self) -> CallToolResult {
        tools::tool_list_stores(&self.stores).await
    }

    /// List every document registered in a store, optionally filtered to a
    /// source, paginated by offset/limit.
    #[tool(
        description = "List every document registered in a store (required 'store': id or name), optionally filtered by 'source' id, paginated by offset/limit (default 50, max 200)."
    )]
    async fn list_documents(
        &self,
        Parameters(args): Parameters<ListDocumentsArgs>,
    ) -> CallToolResult {
        tools::tool_list_documents(&self.stores, self.backend.as_ref(), args).await
    }
}

// `router = self.tool_router` reuses the stored instance field rather than
// rebuilding a fresh router via `Self::tool_router()` on every call (rmcp's
// default when no `router = ...` is given) — the field would otherwise be
// dead weight per rustc's dead-code lint, and reconstructing it per-call is
// wasted work for a routing table that never changes at runtime.
#[tool_handler(router = self.tool_router)]
impl ServerHandler for McpHandler {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new("localdb", env!("CARGO_PKG_VERSION")))
    }
}
